USE NutriTreino;

CREATE TABLE Exercicios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    mets DECIMAL(5,2) NOT NULL
);

INSERT INTO Exercicios (nome, mets)
VALUES
(Ciclismo_geral,	8.0),
(Alongamento_leve,	2.5),
(Aeróbico_degrau_com_degrau_de_6_a_8_polegadas,	8.5),
(Aeróbico_degrau_com_degrau_de_10_a_12_polegadas,	10.0),
(Discoteca_folclórica_praça_dança_em_linha_dança_irlandesa_polca_contra_e_dança_country._,	4.5),
(Dança_Anishinaabe_Jingle_ou_outra_dança_tradicional_indígena_americana,	5.5),
(Esfregar,	3.5),
(Várias_tarefas_domésticas_ao_mesmo_tempo_esforço_leve,	2.5),
(Várias_tarefas_domésticas_ao_mesmo_tempo_esforço_moderado,	3.5),
(Várias_tarefas_domésticas_ao_mesmo_tempo_esforço_vigoroso,	4.0),
(Limpar,	3.5),
(Animais_de_abate,	6.0),
(Alimentação_de_animais,	2.5),
(Regar_plantas,	2.5),
(Construindo_uma_fogueira_dentro,	2.5),
(Carregando_crianças_pequenas,	3.0),
(Cuidados_com_idosos_adultos_com_deficiência_apenas_períodos_ativos,	4.0),
(Reclinável_com_bebê,	1.5),
(Sentado_brincando_com_animais_leve_apenas_períodos_ativos,	2.5),
(Em_pé_brincando_com_animais_leve_apenas_períodos_ativos,	2.8),
(Caminhar/correr_brincar_com_animais_luz_apenas_períodos_ativos,	2.8),
(Caminhar/correr_brincar_com_animais_moderado_apenas_períodos_ativos,	4.0),
(Caminhar/correr_brincar_com_animais_vigoroso_apenas_períodos_ativos_,	5.0),
(Cão_em_pé_–_tomar_banho,	3.5),
(Pintura_(Código_Taylor_630),	4.5),
(Deitado_estranhamente_sem_fazer_nada_deitado_na_cama_acordado_ouvindo_música_(sem_falar_ou_ler),	1.0),
(Sentado_em_silêncio_sentado_fumando_ouvindo_música_(sem_falar_ou_ler)_assistir_a_um_filme_em_um_cinema_,	1.0),
(Cortar_grama_cortador_de_grama,	4.5),
(Gramado_de_ajuntamento_,	4.0),
(Colher_frutas_de_árvores_colher_frutas/legumes_esforço_moderado_,	3.0),
(Em_pé_–_diversos,	2.0),
(Sentado_-_artes_e_ofícios_esforço_leve,	1.5),
(Sentado_-_artes_e_ofícios_esforço_moderado,	2.0),
(Em_pé_-_artes_e_ofícios_esforço_leve,	1.8),
(Em_pé_-_artes_e_ofícios_esforço_moderado,	3.0),
(De_pé_-_artes_e_ofícios_esforço_vigoroso,	3.5),
(Atividades_de_retiro/reunião_familiar_envolvendo_sentar_relaxar_conversar_comer,	1.5),
(Passeios_/_viagens_/_férias_envolvendo_caminhadas_e_passeios,	2.0),
(Acampar_envolvendo_ficar_em_pé_caminhar_sentar_esforço_leve_a_moderado_,	2.5),
(Sentado_em_um_evento_esportivo_espectador,	1.5),
(Padaria_esforço_leve,	2.5),
(Custódia_polimento_do_chão_com_um_amortecedor_elétrico,	3.0),
(Custódia_limpeza_de_pia_e_vaso_sanitário_esforço_leve,	2.5),
(Custódia_poeira_esforço_leve,	2.5),
(Custódia_piso_de_arena_de_penas_esforço_moderado,	4.0),
(Custódia_limpeza_geral_esforço_moderado,	3.5),
(Custódia_limpeza_esforço_moderado,	3.5),
(Custódia_tirar_o_lixo_esforço_moderado,	3.0),
(Custódia_aspiração_esforço_leve,	2.5),
(Custódia_aspiração_esforço_moderado,	3.0),
(Agricultura_perseguição_de_gado_ou_outro_gado_a_cavalo_esforço_moderado,	4.0),
(Agricultura_perseguição_de_gado_ou_outro_gado_condução_esforço_leve,	2.0),
(Agricultura_cuidar_de_animais_(tosa_escovação_tosquia_de_ovelhas_assistência_no_parto_cuidados_médicos_marcação),	6.0),
(Mergulho_livre_ou_mergulho_autônomo_como_homem-rã_(Navy_Seal),	12.0),
(Levantar_itens_continuamente_10–20_libras_com_caminhada_ou_descanso_limitado,	4.0),
(Alfaiataria_tecelagem,	3.5),
(Caminhando_juntando_coisas_no_trabalho_pronto_para_sair_,	3.0),
(Andando_empurrando_uma_cadeira_de_rodas,	4.0),
(Correr_em_um_mini-trampolim,	4.5),
(Tomar_medicação_sentado_ou_em_pé,	1.0),
(Penteado,	2.5),
(Ter_cabelo_ou_unhas_feitas_por_outra_pessoa_sentar_,	1.0),
(Golfe_caminhar_e_carregar_tacos,	4.5),
(Tacos_de_golfe_caminhada_e_puxar,	4.3),
(Patins_(patinação_em_linha),	12.5),
(Tênis_jogo_de_duplas,	5.0),
(Voleibol_jogo_competitivo_em_um_ginásio,	8.0),
(Atletismo_(arremesso_disco_lançamento_de_martelo),	4.0),
(Atletismo_(salto_em_altura_salto_em_distância_salto_triplo_dardo_salto_com_vara)_,	6.0),
(Atletismo_(corrida_com_obstáculos_barreiras),	10.0),
(Andar_de_carro_ou_caminhão,	1.0),
(Andar_de_ônibus,	1.0),
(Carregar/descarregar_um_carro,	3.0),
(Observação_de_aves,	2.5),
(Empurrar_uma_cadeira_de_rodas_ambiente_não_ocupacional,	4.0),
(Caminhando_menos_de_2_0_mph_terreno_plano_passeando_muito_lento,	2.0),
(Caminhada_2_0_mph_nível_ritmo_lento_superfície_firme,	2.5),
(Andar_de_casa_para_carro_ou_ônibus_de_carro_ou_ônibus_para_ir_a_lugares_de_carro_ou_ônibus_de_e_para_o_local_de_trabalho,	2.5),
(Caminhar_até_a_casa_do_vizinho_ou_da_família_por_motivos_sociais,	2.5),
(Passeando_com_o_cachorro,	3.0),
(Caminhando_5.0_mph,	8.0),
(Caminhando_de_e_para_um_banheiro_externo,	2.5),
(Canoagem_colheita_de_arroz_selvagem_derrubando_arroz_dos_talos,	3.3),
(Hidroginástica_calistenia_aquática,	4.0),
(Corrida_aquática,	8.0);